### PR TITLE
Listen to network events

### PR DESCRIPTION
**Pull request by joseluismarti**
To find out about network events, use the [NetworkCallback](https://developer.android.com/reference/android/net/ConnectivityManager.NetworkCallback) class together with [ConnectivityManager.registerDefaultNetworkCallback(NetworkCallback)](https://developer.android.com/reference/android/net/ConnectivityManager#registerDefaultNetworkCallback(android.net.ConnectivityManager.NetworkCallback))

### CODE REVIEW

**Comment by fuzzard** [comment]
I assume you have a purpose in mind for this? What's that use look like?

**Comment by joseluismarti** [comment]
The purpose is that Kodi listens to network status changes, so that if the device changes the default network, the app will do so as well.

A typical example is the device coming within range of a known Wi-Fi access point. The device disconnects from the mobile network, connects to the access point and switches the default network.

**Comment by fuzzard** [comment]
What I'm getting at, is there an implementation you have in Kodi, or is this all theoretical? 

Libandroidjni doesnt have full coverage of the android API, and isn't really intended to. If we don't have a use for it in Kodi that has an implementation, we probably won't add it in here as the API changes in android change so much, that it's possible it gets deprecated before it's even used.

**Comment by joseluismarti** [comment]
I'm working on a proposal for Kodi and I'm ahead with the part that affects the jni library, I hope to have it in a few days

**Pull request merged**
